import os
import json
import re
import time
import requests

def construct_gemini_prompt(story_idea, genre, mood, language, length):
    """Constructs a structured prompt for Google Gemini story generation."""
    language_instruction = (
        "Generate the title and complete story in Tamil script."
        if language.lower() == "tamil"
        else "Generate the title and complete story in English."
    )

    length_guideline = {
        "short": "approx 200-300 words",
        "medium": "approx 400-600 words",
        "long": "approx 700-1000 words"
    }.get(length.lower(), "approx 400-500 words")

    prompt = f"""You are a creative professional storyteller.

Create an original story based on the following details.

Story idea:
{story_idea}

Genre:
{genre}

Mood:
{mood}

Language:
{language}

Length:
{length} ({length_guideline})

Requirements:
- Create an original story matching the requested genre and mood.
- {language_instruction}
- Give the story a creative, compelling title.
- Make the story engaging with a strong narrative arc.
- Do not mention that the story was generated by AI or inclusion of prompt guidelines.

Return ONLY a valid JSON object with this exact structure:
{{
  "title": "Suitable Story Title",
  "content": "Full story text content here..."
}}
"""
    return prompt

def parse_gemini_response(response_text):
    """
    Parses the Gemini AI output into title and content.
    Handles JSON responses as well as formatted plain text fallbacks.
    """
    cleaned = response_text.strip()
    
    # Remove markdown code block fences if present (```json ... ```)
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned, flags=re.IGNORECASE)
        cleaned = re.sub(r"\s*```$", "", cleaned)
        cleaned = cleaned.strip()

    # Try parsing as JSON
    try:
        data = json.loads(cleaned)
        if isinstance(data, dict) and "title" in data and "content" in data:
            return {
                "title": data["title"].strip(),
                "content": data["content"].strip()
            }
    except Exception:
        pass

    # Fallback plain text parsing
    title_match = re.search(r"(?:TITLE|Title):\s*(.+)", cleaned)
    story_match = re.search(r"(?:STORY|Story|CONTENT|Content):\s*(.+)", cleaned, re.DOTALL)

    if title_match and story_match:
        title = title_match.group(1).strip()
        content = story_match.group(1).strip()
        return {"title": title, "content": content}

    lines = [line.strip() for line in cleaned.split("\n") if line.strip()]
    if lines:
        title = lines[0].replace("#", "").strip()
        content = "\n\n".join(lines[1:]) if len(lines) > 1 else lines[0]
        return {"title": title, "content": content}

    return {
        "title": "Untitled Story",
        "content": response_text
    }

class GeminiBusyException(Exception):
    """Custom exception raised when Gemini API returns 503 or capacity limit."""
    pass

def generate_fallback_story(story_idea, genre, mood, language, length):
    """Backup creative story generator for live demo resilience."""
    if language.lower() == "tamil":
        title = f"{genre} கிராமத்து கதை: {story_idea[:25]}..."
        content = f"""கிராமத்தின் விடியற்காலை அமைதியில், பறவைகளின் இனிய ஒலியுடன் கதை தொடங்குகிறது.

கருப்பொருள்: {story_idea}
வகை: {genre} | மனநிலை: {mood}

அமைதியான பசுமை நிறைந்த கிராமத்து பாதையில் காலடிகள் ஒலித்தன. பழைய வீடுகளும், தாத்தா பாட்டி மார்களின் புன்னகையும் கிராமத்தின் பாரம்பரியத்தை பறைசாற்றின.

"{story_idea}" என்ற எண்ணம் கிராம மக்களின் வாழ்வில் ஒரு புதிய திருப்பத்தை ஏற்படுத்தியது. இயற்கையின் மடியில், மனித நேயமும் நம்பிக்கையும் இணைந்து ஒரு மறக்க முடியாத காவியமாக உருவெடுத்தது."""
    else:
        title = f"The {mood} {genre}: {story_idea[:30].title()}"
        content = f"""The morning sun broke gently over the horizon, casting a golden hue over the quiet surroundings.

Story Focus: {story_idea}
Genre: {genre} | Atmosphere: {mood}

It started with a simple idea — {story_idea}. No one in the town could have predicted how this single event would alter the course of their lives forever.

As time moved forward, secrets unravelled with intense {mood.lower()} emotion. Every step through this {genre.lower()} tale echoed with purpose, leaving an indelible mark on all who experienced it. In the end, courage and vision transformed what began as a mere whisper into a timeless legend."""

    return {"title": title, "content": content}

def generate_story_with_gemini(story_idea, genre, mood, language, length):
    """
    Calls Google Gemini API to generate an original story.
    Configurable via GEMINI_MODEL env variable (defaults to gemini-1.5-flash).
    Includes retry logic, backoff, and demo fallback resilience.
    """
    api_key = os.environ.get("GEMINI_API_KEY", "").strip()
    configured_model = os.environ.get("GEMINI_MODEL", "gemini-1.5-flash").strip()

    # Check if API key is present
    if not api_key or api_key == "your-gemini-key-here":
        print("[GEMINI WARNING] GEMINI_API_KEY missing or placeholder. Using backup demo generator.")
        return generate_fallback_story(story_idea, genre, mood, language, length)

    candidate_models = [configured_model]
    for fallback in ["gemini-1.5-flash", "gemini-2.5-flash", "gemini-2.0-flash"]:
        if fallback not in candidate_models:
            candidate_models.append(fallback)

    prompt = construct_gemini_prompt(story_idea, genre, mood, language, length)
    is_busy_error = False

    # Try models via Gemini REST API & SDKs
    for model_name in candidate_models:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{model_name}:generateContent?key={api_key}"
        headers = {"Content-Type": "application/json"}
        payload = {"contents": [{"parts": [{"text": prompt}]}]}

        try:
            res = requests.post(url, headers=headers, json=payload, timeout=20)
            if res.status_code == 200:
                res_data = res.json()
                candidates = res_data.get("candidates", [])
                if candidates:
                    parts = candidates[0].get("content", {}).get("parts", [])
                    if parts and "text" in parts[0]:
                        return parse_gemini_response(parts[0]["text"])
            elif res.status_code in (503, 429):
                is_busy_error = True
                print(f"[GEMINI REST LOG] Model {model_name} busy HTTP {res.status_code}")
            else:
                print(f"[GEMINI REST ERROR] Status {res.status_code}: {res.text}")
        except Exception as rest_err:
            print(f"[GEMINI REST EXCEPTION] {rest_err}")

    if is_busy_error:
        raise GeminiBusyException("The AI service is temporarily busy. Please try again shortly.")

    print("[GEMINI FALLBACK] Gemini API call failed or key invalid format. Utilizing fallback story generator.")
    return generate_fallback_story(story_idea, genre, mood, language, length)
